package com.example.demo.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContentEntityExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public ContentEntityExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andContentIdIsNull() {
			addCriterion("content_id is null");
			return (Criteria) this;
		}

		public Criteria andContentIdIsNotNull() {
			addCriterion("content_id is not null");
			return (Criteria) this;
		}

		public Criteria andContentIdEqualTo(Integer value) {
			addCriterion("content_id =", value, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdNotEqualTo(Integer value) {
			addCriterion("content_id <>", value, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdGreaterThan(Integer value) {
			addCriterion("content_id >", value, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("content_id >=", value, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdLessThan(Integer value) {
			addCriterion("content_id <", value, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdLessThanOrEqualTo(Integer value) {
			addCriterion("content_id <=", value, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdIn(List<Integer> values) {
			addCriterion("content_id in", values, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdNotIn(List<Integer> values) {
			addCriterion("content_id not in", values, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdBetween(Integer value1, Integer value2) {
			addCriterion("content_id between", value1, value2, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdNotBetween(Integer value1, Integer value2) {
			addCriterion("content_id not between", value1, value2, "contentId");
			return (Criteria) this;
		}

		public Criteria andListIdIsNull() {
			addCriterion("list_id is null");
			return (Criteria) this;
		}

		public Criteria andListIdIsNotNull() {
			addCriterion("list_id is not null");
			return (Criteria) this;
		}

		public Criteria andListIdEqualTo(Integer value) {
			addCriterion("list_id =", value, "listId");
			return (Criteria) this;
		}

		public Criteria andListIdNotEqualTo(Integer value) {
			addCriterion("list_id <>", value, "listId");
			return (Criteria) this;
		}

		public Criteria andListIdGreaterThan(Integer value) {
			addCriterion("list_id >", value, "listId");
			return (Criteria) this;
		}

		public Criteria andListIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("list_id >=", value, "listId");
			return (Criteria) this;
		}

		public Criteria andListIdLessThan(Integer value) {
			addCriterion("list_id <", value, "listId");
			return (Criteria) this;
		}

		public Criteria andListIdLessThanOrEqualTo(Integer value) {
			addCriterion("list_id <=", value, "listId");
			return (Criteria) this;
		}

		public Criteria andListIdIn(List<Integer> values) {
			addCriterion("list_id in", values, "listId");
			return (Criteria) this;
		}

		public Criteria andListIdNotIn(List<Integer> values) {
			addCriterion("list_id not in", values, "listId");
			return (Criteria) this;
		}

		public Criteria andListIdBetween(Integer value1, Integer value2) {
			addCriterion("list_id between", value1, value2, "listId");
			return (Criteria) this;
		}

		public Criteria andListIdNotBetween(Integer value1, Integer value2) {
			addCriterion("list_id not between", value1, value2, "listId");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andContentTextIsNull() {
			addCriterion("content_text is null");
			return (Criteria) this;
		}

		public Criteria andContentTextIsNotNull() {
			addCriterion("content_text is not null");
			return (Criteria) this;
		}

		public Criteria andContentTextEqualTo(String value) {
			addCriterion("content_text =", value, "contentText");
			return (Criteria) this;
		}

		public Criteria andContentTextNotEqualTo(String value) {
			addCriterion("content_text <>", value, "contentText");
			return (Criteria) this;
		}

		public Criteria andContentTextGreaterThan(String value) {
			addCriterion("content_text >", value, "contentText");
			return (Criteria) this;
		}

		public Criteria andContentTextGreaterThanOrEqualTo(String value) {
			addCriterion("content_text >=", value, "contentText");
			return (Criteria) this;
		}

		public Criteria andContentTextLessThan(String value) {
			addCriterion("content_text <", value, "contentText");
			return (Criteria) this;
		}

		public Criteria andContentTextLessThanOrEqualTo(String value) {
			addCriterion("content_text <=", value, "contentText");
			return (Criteria) this;
		}

		public Criteria andContentTextLike(String value) {
			addCriterion("content_text like", value, "contentText");
			return (Criteria) this;
		}

		public Criteria andContentTextNotLike(String value) {
			addCriterion("content_text not like", value, "contentText");
			return (Criteria) this;
		}

		public Criteria andContentTextIn(List<String> values) {
			addCriterion("content_text in", values, "contentText");
			return (Criteria) this;
		}

		public Criteria andContentTextNotIn(List<String> values) {
			addCriterion("content_text not in", values, "contentText");
			return (Criteria) this;
		}

		public Criteria andContentTextBetween(String value1, String value2) {
			addCriterion("content_text between", value1, value2, "contentText");
			return (Criteria) this;
		}

		public Criteria andContentTextNotBetween(String value1, String value2) {
			addCriterion("content_text not between", value1, value2, "contentText");
			return (Criteria) this;
		}

		public Criteria andIsEnabledIsNull() {
			addCriterion("is_enabled is null");
			return (Criteria) this;
		}

		public Criteria andIsEnabledIsNotNull() {
			addCriterion("is_enabled is not null");
			return (Criteria) this;
		}

		public Criteria andIsEnabledEqualTo(Boolean value) {
			addCriterion("is_enabled =", value, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledNotEqualTo(Boolean value) {
			addCriterion("is_enabled <>", value, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledGreaterThan(Boolean value) {
			addCriterion("is_enabled >", value, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_enabled >=", value, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledLessThan(Boolean value) {
			addCriterion("is_enabled <", value, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledLessThanOrEqualTo(Boolean value) {
			addCriterion("is_enabled <=", value, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledIn(List<Boolean> values) {
			addCriterion("is_enabled in", values, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledNotIn(List<Boolean> values) {
			addCriterion("is_enabled not in", values, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledBetween(Boolean value1, Boolean value2) {
			addCriterion("is_enabled between", value1, value2, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andIsEnabledNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_enabled not between", value1, value2, "isEnabled");
			return (Criteria) this;
		}

		public Criteria andUpdateTimestampIsNull() {
			addCriterion("update_timestamp is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimestampIsNotNull() {
			addCriterion("update_timestamp is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimestampEqualTo(Date value) {
			addCriterion("update_timestamp =", value, "updateTimestamp");
			return (Criteria) this;
		}

		public Criteria andUpdateTimestampNotEqualTo(Date value) {
			addCriterion("update_timestamp <>", value, "updateTimestamp");
			return (Criteria) this;
		}

		public Criteria andUpdateTimestampGreaterThan(Date value) {
			addCriterion("update_timestamp >", value, "updateTimestamp");
			return (Criteria) this;
		}

		public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
			addCriterion("update_timestamp >=", value, "updateTimestamp");
			return (Criteria) this;
		}

		public Criteria andUpdateTimestampLessThan(Date value) {
			addCriterion("update_timestamp <", value, "updateTimestamp");
			return (Criteria) this;
		}

		public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
			addCriterion("update_timestamp <=", value, "updateTimestamp");
			return (Criteria) this;
		}

		public Criteria andUpdateTimestampIn(List<Date> values) {
			addCriterion("update_timestamp in", values, "updateTimestamp");
			return (Criteria) this;
		}

		public Criteria andUpdateTimestampNotIn(List<Date> values) {
			addCriterion("update_timestamp not in", values, "updateTimestamp");
			return (Criteria) this;
		}

		public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
			addCriterion("update_timestamp between", value1, value2, "updateTimestamp");
			return (Criteria) this;
		}

		public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
			addCriterion("update_timestamp not between", value1, value2, "updateTimestamp");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table todo_content
     *
     * @mbg.generated do_not_delete_during_merge Sun Mar 14 19:14:37 JST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}