package com.example.demo.repository;

import com.example.demo.dto.ContentEntityExample;
import com.example.demo.entity.ContentEntity;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	long countByExample(ContentEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	int deleteByExample(ContentEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	int deleteByPrimaryKey(Integer contentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	int insert(ContentEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	int insertSelective(ContentEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	List<ContentEntity> selectByExample(ContentEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	ContentEntity selectByPrimaryKey(Integer contentId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	int updateByExampleSelective(@Param("record") ContentEntity record, @Param("example") ContentEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	int updateByExample(@Param("record") ContentEntity record, @Param("example") ContentEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	int updateByPrimaryKeySelective(ContentEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_content
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	int updateByPrimaryKey(ContentEntity record);
}