package com.example.demo.repository;

import org.apache.ibatis.annotations.Mapper;

import com.example.demo.entity.ListPrimaryEntity;

@Mapper
public interface ListPrimaryEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int deleteByPrimaryKey(Integer listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int insert(ListPrimaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int insertSelective(ListPrimaryEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    ListPrimaryEntity selectByPrimaryKey(Integer listId);
}