package com.example.demo.repository;

import org.apache.ibatis.annotations.Mapper;

import com.example.demo.entity.SpacePrimaryEntity;

@Mapper
public interface SpacePrimaryEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_space
	 * @mbg.generated  Fri Apr 30 22:33:48 JST 2021
	 */
	int deleteByPrimaryKey(Integer spaceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_space
	 * @mbg.generated  Fri Apr 30 22:33:48 JST 2021
	 */
	int insert(SpacePrimaryEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table todo_space
	 * @mbg.generated  Fri Apr 30 22:33:48 JST 2021
	 */
	int insertSelective(SpacePrimaryEntity record);
}