package com.example.demo.repository;

import com.example.demo.dto.SpaceEntityExample;
import com.example.demo.entity.SpaceEntity;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SpaceEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_space_details
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    long countByExample(SpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_space_details
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int deleteByExample(SpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_space_details
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int deleteByPrimaryKey(Integer scopeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_space_details
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int insert(SpaceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_space_details
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int insertSelective(SpaceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_space_details
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    List<SpaceEntity> selectByExample(SpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_space_details
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    SpaceEntity selectByPrimaryKey(Integer scopeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_space_details
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int updateByExampleSelective(@Param("record") SpaceEntity record, @Param("example") SpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_space_details
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int updateByExample(@Param("record") SpaceEntity record, @Param("example") SpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_space_details
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int updateByPrimaryKeySelective(SpaceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_space_details
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int updateByPrimaryKey(SpaceEntity record);
}