package com.example.demo.repository;

import com.example.demo.entity.SpacePrimaryEnti;

public interface SpacePrimaryEntiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_space
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int deleteByPrimaryKey(Integer spaceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_space
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int insert(SpacePrimaryEnti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_space
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int insertSelective(SpacePrimaryEnti record);
}