package com.example.demo.repository;

import com.example.demo.entity.UserEntity;
import com.example.demo.entity.UserEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserEntityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Mar 14 11:52:35 JST 2021
	 */
	long countByExample(UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Mar 14 11:52:35 JST 2021
	 */
	int deleteByExample(UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Mar 14 11:52:35 JST 2021
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Mar 14 11:52:35 JST 2021
	 */
	int insert(UserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Mar 14 11:52:35 JST 2021
	 */
	int insertSelective(UserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Mar 14 11:52:35 JST 2021
	 */
	List<UserEntity> selectByExample(UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Mar 14 11:52:35 JST 2021
	 */
	UserEntity selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Mar 14 11:52:35 JST 2021
	 */
	int updateByExampleSelective(@Param("record") UserEntity record, @Param("example") UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Mar 14 11:52:35 JST 2021
	 */
	int updateByExample(@Param("record") UserEntity record, @Param("example") UserEntityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Mar 14 11:52:35 JST 2021
	 */
	int updateByPrimaryKeySelective(UserEntity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table users
	 * @mbg.generated  Sun Mar 14 11:52:35 JST 2021
	 */
	int updateByPrimaryKey(UserEntity record);
}