package com.example.demo.repository;

import com.example.demo.dto.UserInSpaceEntityExample;
import com.example.demo.entity.UserInSpaceEntity;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserInSpaceEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    long countByExample(UserInSpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int deleteByExample(UserInSpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int deleteByPrimaryKey(@Param("spaceId") Integer spaceId, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int insert(UserInSpaceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int insertSelective(UserInSpaceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    List<UserInSpaceEntity> selectByExample(UserInSpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    UserInSpaceEntity selectByPrimaryKey(@Param("spaceId") Integer spaceId, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int updateByExampleSelective(@Param("record") UserInSpaceEntity record, @Param("example") UserInSpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int updateByExample(@Param("record") UserInSpaceEntity record, @Param("example") UserInSpaceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int updateByPrimaryKeySelective(UserInSpaceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table have_user_list
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    int updateByPrimaryKey(UserInSpaceEntity record);
}