package com.example.demo.entity;

public class ListPrimaryEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.list_id
     *
     * @mbg.generated Fri Apr 30 22:14:58 JST 2021
     */
    private Integer listId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.space_Id
     *
     * @mbg.generated Fri Apr 30 22:14:58 JST 2021
     */
    private Integer spaceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.list_id
     *
     * @return the value of todo_list.list_id
     *
     * @mbg.generated Fri Apr 30 22:14:58 JST 2021
     */
    public Integer getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.list_id
     *
     * @param listId the value for todo_list.list_id
     *
     * @mbg.generated Fri Apr 30 22:14:58 JST 2021
     */
    public void setListId(Integer listId) {
        this.listId = listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.space_Id
     *
     * @return the value of todo_list.space_Id
     *
     * @mbg.generated Fri Apr 30 22:14:58 JST 2021
     */
    public Integer getSpaceId() {
        return spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.space_Id
     *
     * @param spaceId the value for todo_list.space_Id
     *
     * @mbg.generated Fri Apr 30 22:14:58 JST 2021
     */
    public void setSpaceId(Integer spaceId) {
        this.spaceId = spaceId;
    }
}