package com.example.demo.entity;

import java.util.Date;

public class ListEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list_details.list_id
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    private Integer listId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list_details.list_name
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    private String listName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list_details.list_date
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    private Date listDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list_details.is_alarm
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    private Boolean isAlarm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list_details.is_enabled
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    private Boolean isEnabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list_details.update_timestamp
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list_details.is_alarm
     *
     * @return the value of todo_list_details.is_alarm
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    public Boolean getIsAlarm() {
        return isAlarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list_details.is_enabled
     *
     * @return the value of todo_list_details.is_enabled
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list_details.list_date
     *
     * @return the value of todo_list_details.list_date
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    public Date getListDate() {
        return listDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list_details.list_id
     *
     * @return the value of todo_list_details.list_id
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    public Integer getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list_details.list_name
     *
     * @return the value of todo_list_details.list_name
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    public String getListName() {
        return listName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list_details.update_timestamp
     *
     * @return the value of todo_list_details.update_timestamp
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list_details.is_alarm
     *
     * @param isAlarm the value for todo_list_details.is_alarm
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    public void setIsAlarm(Boolean isAlarm) {
        this.isAlarm = isAlarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list_details.is_enabled
     *
     * @param isEnabled the value for todo_list_details.is_enabled
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list_details.list_date
     *
     * @param listDate the value for todo_list_details.list_date
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    public void setListDate(Date listDate) {
        this.listDate = listDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list_details.list_id
     *
     * @param listId the value for todo_list_details.list_id
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    public void setListId(Integer listId) {
        this.listId = listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list_details.list_name
     *
     * @param listName the value for todo_list_details.list_name
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    public void setListName(String listName) {
        this.listName = listName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list_details.update_timestamp
     *
     * @param updateTimestamp the value for todo_list_details.update_timestamp
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}