package com.example.demo.entity;

import java.util.Date;

public class SpaceEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column todo_space_details.space_id
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	private Integer spaceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column todo_space_details.space_name
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	private String spaceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column todo_space_details.scope_id
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	private Integer scopeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column todo_space_details.is_simple
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	private Boolean isSimple;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column todo_space_details.is_enabled
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	private Boolean isEnabled;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column todo_space_details.update_timestampe
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	private Date updateTimestampe;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column todo_space_details.space_id
	 * @return  the value of todo_space_details.space_id
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	public Integer getSpaceId() {
		return spaceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column todo_space_details.space_id
	 * @param spaceId  the value for todo_space_details.space_id
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	public void setSpaceId(Integer spaceId) {
		this.spaceId = spaceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column todo_space_details.space_name
	 * @return  the value of todo_space_details.space_name
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	public String getSpaceName() {
		return spaceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column todo_space_details.space_name
	 * @param spaceName  the value for todo_space_details.space_name
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	public void setSpaceName(String spaceName) {
		this.spaceName = spaceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column todo_space_details.scope_id
	 * @return  the value of todo_space_details.scope_id
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	public Integer getScopeId() {
		return scopeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column todo_space_details.scope_id
	 * @param scopeId  the value for todo_space_details.scope_id
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	public void setScopeId(Integer scopeId) {
		this.scopeId = scopeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column todo_space_details.is_simple
	 * @return  the value of todo_space_details.is_simple
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	public Boolean getIsSimple() {
		return isSimple;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column todo_space_details.is_simple
	 * @param isSimple  the value for todo_space_details.is_simple
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	public void setIsSimple(Boolean isSimple) {
		this.isSimple = isSimple;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column todo_space_details.is_enabled
	 * @return  the value of todo_space_details.is_enabled
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	public Boolean getIsEnabled() {
		return isEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column todo_space_details.is_enabled
	 * @param isEnabled  the value for todo_space_details.is_enabled
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	public void setIsEnabled(Boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column todo_space_details.update_timestampe
	 * @return  the value of todo_space_details.update_timestampe
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	public Date getUpdateTimestampe() {
		return updateTimestampe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column todo_space_details.update_timestampe
	 * @param updateTimestampe  the value for todo_space_details.update_timestampe
	 * @mbg.generated  Fri Apr 30 22:14:58 JST 2021
	 */
	public void setUpdateTimestampe(Date updateTimestampe) {
		this.updateTimestampe = updateTimestampe;
	}
}