package com.example.demo.entity;

import java.util.Date;

public class SpaceEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_space_details.space_id
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    private Integer spaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_space_details.space_name
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    private String spaceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_space_details.scope_Id
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    private Integer scopeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_space_details.is_simple
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    private Boolean isSimple;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_space_details.is_enable
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    private Boolean isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_space_details.update_timestamp
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_space_details.is_enable
     *
     * @return the value of todo_space_details.is_enable
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    public Boolean getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_space_details.is_simple
     *
     * @return the value of todo_space_details.is_simple
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    public Boolean getIsSimple() {
        return isSimple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_space_details.scope_Id
     *
     * @return the value of todo_space_details.scope_Id
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    public Integer getScopeId() {
        return scopeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_space_details.space_id
     *
     * @return the value of todo_space_details.space_id
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    public Integer getSpaceId() {
        return spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_space_details.space_name
     *
     * @return the value of todo_space_details.space_name
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    public String getSpaceName() {
        return spaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_space_details.update_timestamp
     *
     * @return the value of todo_space_details.update_timestamp
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_space_details.is_enable
     *
     * @param isEnable the value for todo_space_details.is_enable
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    public void setIsEnable(Boolean isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_space_details.is_simple
     *
     * @param isSimple the value for todo_space_details.is_simple
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    public void setIsSimple(Boolean isSimple) {
        this.isSimple = isSimple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_space_details.scope_Id
     *
     * @param scopeId the value for todo_space_details.scope_Id
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    public void setScopeId(Integer scopeId) {
        this.scopeId = scopeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_space_details.space_id
     *
     * @param spaceId the value for todo_space_details.space_id
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    public void setSpaceId(Integer spaceId) {
        this.spaceId = spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_space_details.space_name
     *
     * @param spaceName the value for todo_space_details.space_name
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    public void setSpaceName(String spaceName) {
        this.spaceName = spaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_space_details.update_timestamp
     *
     * @param updateTimestamp the value for todo_space_details.update_timestamp
     *
     * @mbg.generated Sat Mar 20 11:55:21 JST 2021
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}