package com.example.demo.entity;

public class SpacePrimaryEnti {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_space.space_id
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    private Integer spaceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_space.space_id
     *
     * @return the value of todo_space.space_id
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    public Integer getSpaceId() {
        return spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_space.space_id
     *
     * @param spaceId the value for todo_space.space_id
     *
     * @mbg.generated Sun Mar 14 11:52:35 JST 2021
     */
    public void setSpaceId(Integer spaceId) {
        this.spaceId = spaceId;
    }
}