package com.example.demo.entity;

import java.util.Date;

public class TodoListEachUserEntity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column todo_list_eacch_user.user_id
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column todo_list_eacch_user.space_id
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	private Integer spaceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column todo_list_eacch_user.list_id
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	private Integer listId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column todo_list_eacch_user.list_name
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	private String listName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column todo_list_eacch_user.list_date
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	private Date listDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column todo_list_eacch_user.list_date
	 * @return  the value of todo_list_eacch_user.list_date
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public Date getListDate() {
		return listDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column todo_list_eacch_user.list_id
	 * @return  the value of todo_list_eacch_user.list_id
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public Integer getListId() {
		return listId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column todo_list_eacch_user.list_name
	 * @return  the value of todo_list_eacch_user.list_name
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public String getListName() {
		return listName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column todo_list_eacch_user.space_id
	 * @return  the value of todo_list_eacch_user.space_id
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public Integer getSpaceId() {
		return spaceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column todo_list_eacch_user.user_id
	 * @return  the value of todo_list_eacch_user.user_id
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column todo_list_eacch_user.list_date
	 * @param listDate  the value for todo_list_eacch_user.list_date
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public void setListDate(Date listDate) {
		this.listDate = listDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column todo_list_eacch_user.list_id
	 * @param listId  the value for todo_list_eacch_user.list_id
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public void setListId(Integer listId) {
		this.listId = listId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column todo_list_eacch_user.list_name
	 * @param listName  the value for todo_list_eacch_user.list_name
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public void setListName(String listName) {
		this.listName = listName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column todo_list_eacch_user.space_id
	 * @param spaceId  the value for todo_list_eacch_user.space_id
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public void setSpaceId(Integer spaceId) {
		this.spaceId = spaceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column todo_list_eacch_user.user_id
	 * @param userId  the value for todo_list_eacch_user.user_id
	 * @mbg.generated  Tue Mar 16 20:39:48 JST 2021
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}
}